### ISSUE TITLE
Problem with Scala Reflection

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#175]
Appeared in #174.
It is somehow related to the question
http://stackoverflow.com/questions/32118877/compiler-doesnt-generate-a-field-for-implicit-val-when-an-implicit-val-with-the
See `ReflectionUtil.scala`

```
Caused by: scala.ScalaReflectionException: <none> is not a term
	at scala.reflect.api.Symbols$SymbolApi$class.asTerm(Symbols.scala:199)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asTerm(Symbols.scala:84)
	at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1$$anonfun$1.applyOrElse(ReflectionUtil.scala:56)
	at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1$$anonfun$1.applyOrElse(ReflectionUtil.scala:55)
...
```

**Comment by klinov** [comment]
I will update this issue, I think it should be assigned to @alexeyr 
I have a test that is not working
https://github.com/klinov/scalan/tree/problem-collection-pairIf
```
[info]   Cause: scala.ScalaReflectionException: <none> is not a term
[info]   at scala.reflect.api.Symbols$SymbolApi$class.asTerm(Symbols.scala:199)
[info]   at scala.reflect.internal.Symbols$SymbolContextApiImpl.asTerm(Symbols.scala:82)
[info]   at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1$$anonfun$1.applyOrElse(ReflectionUtil.scala:56)
[info]   at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1$$anonfun$1.applyOrElse(ReflectionUtil.scala:55)
[info]   at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
[info]   at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:743)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
[info]   at scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:132)
[info]   at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:104)
```
