### ISSUE TITLE
Problem with getResultElem for a method of companion

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan#186]
```scala
class ExampleStagingTests extends BaseViewTests {
  test("matrix_convertion") {
    import scalan._
    import scalan.linalgebra._

    class Ctx extends MatricesDslExp { override def isInvokeEnabled(d: Def[_], m: Method) = false }
    val ctx = new Ctx
    import ctx._
    def sparseData2denseData = fun { data: Rep[SparseVectorData[Double]] =>
      val v = SparseVector(data)
      DenseVector(v.items).toData
    }
    emit("sparseData2denseData", sparseData2denseData)
  }
}
```

Staging sparseData2denseDataNoInvoke failed. 
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:496)
	at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
	at org.scalatest.Assertions$class.fail(Assertions.scala:1348)
	at org.scalatest.FunSuite.fail(FunSuite.scala:1555)
	at scalan.TestContexts$class.stage(TestContexts.scala:18)
	at scalan.BaseCtxTests.stage(TestContexts.scala:72)
	at scalan.examples.ExampleStagingTests$$anonfun$1.apply$mcV$sp(ExampleStagingTests.scala:29)
	at scalan.examples.ExampleStagingTests$$anonfun$1.apply(ExampleStagingTests.scala:13)
	at scalan.examples.ExampleStagingTests$$anonfun$1.apply(ExampleStagingTests.scala:13)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at scalan.BaseTests.scalan$TestsUtil$$super$withFixture(BaseTests.scala:50)
	at scalan.TestsUtil$class.withFixture(BaseTests.scala:30)
	at scalan.BaseTests.withFixture(BaseTests.scala:50)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: scalan.Base$StagingException: getResultElem for s11.apply(s9, BaseElem{Double}) failed
	at scalan.Base$class.$bang$bang$bang(Base.scala:40)
	at scalan.Scalan.$bang$bang$bang(Scalan.scala:11)
	at scalan.ProxyExp$class.throwInvocationException(Proxy.scala:796)
	at scalan.ScalanExp.throwInvocationException(Scalan.scala:96)
	at scalan.ProxyExp$class.mkMethodCall(Proxy.scala:160)
	at scalan.ScalanExp.mkMethodCall(Scalan.scala:96)
	at scalan.ProxyExp$ExpInvocationHandler.invokeMethodOfVar(Proxy.scala:790)
	at scalan.ProxyExp$ExpInvocationHandler.invoke(Proxy.scala:782)
	at scalan.linalgebra.impl.VectorsAbs$SparseVectorCompanionAbs$$EnhancerByCGLIB$$894a319d.apply(<generated>)
	at scalan.examples.ExampleStagingTests$$anonfun$1$$anonfun$scalan$examples$ExampleStagingTests$$anonfun$$sparseData2denseData$1$1.apply(ExampleStagingTests.scala:24)
	at scalan.examples.ExampleStagingTests$$anonfun$1$$anonfun$scalan$examples$ExampleStagingTests$$anonfun$$sparseData2denseData$1$1.apply(ExampleStagingTests.scala:23)
	at scalan.primitives.FunctionsExp$class.scalan$primitives$FunctionsExp$$executeFunction(Functions.scala:338)
	at scalan.primitives.FunctionsExp$$anonfun$4.apply(Functions.scala:356)
	at scalan.primitives.FunctionsExp$$anonfun$4.apply(Functions.scala:356)
	at scalan.primitives.EffectsExp$class.reifySubGraph(Effects.scala:56)
	at scalan.ScalanExp.reifySubGraph(Scalan.scala:96)
	at scalan.primitives.EffectsExp$class.reifyEffects(Effects.scala:640)
	at scalan.ScalanExp.reifyEffects(Scalan.scala:96)
	at scalan.primitives.FunctionsExp$class.reifyFunction(Functions.scala:356)
	at scalan.ScalanExp.reifyFunction(Scalan.scala:96)
	at scalan.primitives.FunctionsExp$class.scalan$primitives$FunctionsExp$$lambda(Functions.scala:320)
	at scalan.primitives.FunctionsExp$class.mkLambda(Functions.scala:299)
	at scalan.ScalanExp.mkLambda(Scalan.scala:96)
	at scalan.ScalanExp.mkLambda(Scalan.scala:96)
	at scalan.primitives.Functions$class.fun(Functions.scala:20)
	at scalan.Scalan.fun(Scalan.scala:11)
	at scalan.examples.ExampleStagingTests$$anonfun$1.scalan$examples$ExampleStagingTests$$anonfun$$sparseData2denseData$1(ExampleStagingTests.scala:23)
	at scalan.examples.ExampleStagingTests$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ExampleStagingTests.scala:29)
	at scalan.examples.ExampleStagingTests$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ExampleStagingTests.scala:29)
	at scalan.TestContexts$$anonfun$1.apply(TestContexts.scala:13)
	at scalan.TestContexts$$anonfun$1.apply(TestContexts.scala:13)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at scalan.TestContexts$class.stage(TestContexts.scala:13)
	... 55 more
Caused by: scalan.Base$StagingException: Failure to get result elem for method public java.lang.Object scalan.linalgebra.impl.VectorsAbs$SparseVectorCompanionAbs.apply(java.lang.Object,scalan.Elems$Elem) on type VectorsAbs.this.SparseVectorCompanionAbs
Return type: VectorsAbs.this.Rep[VectorsAbs.this.SparseVector[T]]
	at scalan.Base$class.$bang$bang$bang(Base.scala:40)
	at scalan.Scalan.$bang$bang$bang(Scalan.scala:11)
	at scalan.ProxyExp$class.getResultElem(Proxy.scala:692)
	at scalan.ScalanExp.scalan$ViewsDslExp$$super$getResultElem(Scalan.scala:96)
	at scalan.ViewsDslExp$class.getResultElem(Views.scala:460)
	at scalan.examples.ExampleStagingTests$$anonfun$1$Ctx$1.scalan$collections$CollectionsDslExp$$super$getResultElem(ExampleStagingTests.scala:17)
	at scalan.collections.CollectionsDslExp$class.getResultElem(Collections.scala:685)
	at scalan.examples.ExampleStagingTests$$anonfun$1$Ctx$1.getResultElem(ExampleStagingTests.scala:17)
	at scalan.ProxyExp$class.mkMethodCall(Proxy.scala:157)
	... 87 more
Caused by: java.lang.NoSuchMethodException: scalan.Elems$PairElem.eItem()
	at java.lang.Class.getMethod(Class.java:1786)
	at scalan.ProxyExp$class.getParameterTypeDesc(Proxy.scala:503)
	at scalan.ScalanExp.getParameterTypeDesc(Scalan.scala:96)
	at scalan.ProxyExp$$anonfun$17.apply(Proxy.scala:489)
	at scalan.ProxyExp$$anonfun$17.apply(Proxy.scala:481)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:373)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.reflect.internal.Scopes$Scope.flatMap(Scopes.scala:51)
	at scalan.ProxyExp$class.extractParts(Proxy.scala:481)
	at scalan.ProxyExp$class.extractElems(Proxy.scala:524)
	at scalan.ProxyExp$class.getResultElem(Proxy.scala:679)
	... 93 more

Process finished with exit code 0

**Comment by alexeyr** [comment]
The problem is that `...CompanionAbs.apply` is overloaded and doesn't have `@OverloadId`. Adding `@OverloadId("fromData")` to `def apply[T](p: Rep[SparseVectorData[T]])(implicit eT: Elem[T]): Rep[SparseVector[T]]` fixes the problem (in this case, at least). Maybe, even better to rename this overload to `fromData`. Generated here: https://github.com/scalan/scalan/blob/929fc17477b31a65aa94a964291feed9f5f70383/meta/src/main/scala/scalan/meta/ScalanCodegen.scala#L694.
